"""Layout strategy models for Phase 4 LLM-driven layout."""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal, Any, Dict


class LayoutStrategy(BaseModel):
    """High-level layout strategy generated by LLM.

    LLM decides 'how to arrange' (layout strategy),
    code decides 'exact positions' (coordinate calculation).
    """
    type: Literal[
        "hero-first", "gallery-grid", "asymmetric",
        "centerpiece", "magazine", "timeline", "minimal-list",
    ] = Field(..., description="Layout strategy type")

    primary_component: Optional[str] = Field(
        None, description="Which component type is the focal point"
    )
    spacing: Literal["tight", "normal", "loose"] = Field(
        default="normal", description="Spacing between components"
    )
    symmetry: Literal["symmetric", "asymmetric", "dynamic"] = Field(
        default="symmetric", description="Visual symmetry"
    )
    alignment: Literal["center", "left", "staggered"] = Field(
        default="center", description="Component alignment"
    )
    responsive_behavior: Literal[
        "scale", "reflow-columns", "hide-secondary", "stack"
    ] = Field(default="reflow-columns", description="Responsive breakpoint behavior")
    reason: str = Field(default="", description="LLM explanation for this strategy")


class LayoutResult(BaseModel):
    """Result of strategy-driven layout computation."""
    components: List[Dict[str, Any]] = Field(
        ..., description="Components with updated positions"
    )
    strategy_applied: str = Field(
        ..., description="Name of the layout strategy that was applied"
    )
    warnings: List[str] = Field(
        default_factory=list, description="Non-fatal layout warnings"
    )
