"""Planner Agent - Intent recognition and task planning.

Phase 2: Analyzes user input, extracts actionable plan for the Builder/Modify pipeline.
Replaces the old "keyword-based intent" with structured planning.
"""

from typing import Dict, Any, Optional, List
from pydantic import BaseModel, Field

from .base import BaseAgent, AgentType, AgentResponse
from ..memory.session import Session, SessionState
from ..tools.theme_matcher import ThemeMatcherTool, ThemeMatcherInput, THEME_CATALOG


# ============================================================================
# Plan model
# ============================================================================

class ActionItem(BaseModel):
    """A single action in the plan."""
    tool: str = Field(..., description="Tool to use")
    args: Dict[str, Any] = Field(default_factory=dict, description="Tool arguments")
    description: str = Field(default="", description="What this step does")


class ExecutionPlan(BaseModel):
    """Execution plan generated by Planner Agent."""
    intent: str = Field(
        default="chat",
        description="new_page / modify_page / query / chat"
    )
    theme_id: str = Field(default="sakura", description="Target theme")
    skill_id: Optional[str] = Field(None, description="Target skill (e.g., sakura-style)")
    component_types: List[str] = Field(
        default_factory=list, description="Expected component types"
    )
    actions: List[ActionItem] = Field(
        default_factory=list, description="Ordered action list"
    )
    estimated_steps: int = Field(default=0, description="Estimated number of steps")
    confidence: float = Field(default=0.5, description="Plan confidence 0-1")


# ============================================================================
# Planning prompts
# ============================================================================

PLANNER_SYSTEM_PROMPT = """你是 Heya Studio 的计划专家。

你的任务是分析用户需求，生成结构化的执行计划。

## 可用主题
sakura (樱花), lavender (薰衣草), mint (薄荷), cream (奶油), night (赛博), pixel (像素), mono (极简), millennial (千禧)

## 可用组件类型
hero-section, oshi-card, attribute-wall, tag-group, music-player, social-links, quote, friends-list, media-list, merchandise-card, guestbook, watchlist, gallery, achievement-badges, memorial-calendar, cp-card, media-card, support-record, divider, spacer

## 规划规则
1. 生成新页面: intent = "new_page", 需要选主题和组件
2. 修改现有页面: intent = "modify_page", 需要定位要改的部分
3. 查询: intent = "query", 不需要生成
4. 闲聊: intent = "chat", 不需要生成

## 输出格式 (JSON)
{
  "intent": "new_page",
  "theme_id": "sakura",
  "skill_id": "sakura-style",
  "component_types": ["hero-section", "oshi-card", "quote", "social-links"],
  "actions": [
    {"tool": "suggest_components", "args": {"profile": {...}}, "description": "推荐组件"},
    {"tool": "assemble_config", "args": {...}, "description": "拼装配置"},
    {"tool": "auto_layout", "args": {...}, "description": "自动布局"},
  ],
  "estimated_steps": 4,
  "confidence": 0.9
}"""


# ============================================================================
# Planner Agent
# ============================================================================

class PlannerAgent(BaseAgent):
    """Planner Agent - Intent recognition and task planning."""

    agent_type = AgentType.ROUTER
    name = "Planner Agent"
    description = "分析用户需求,生成执行计划"
    max_iterations = 1
    timeout_ms = 10000

    def __init__(self, llm_client=None, memory=None, tool_registry=None):
        # PlannerAgent can work without LLM (rule-based fallback)
        self.llm = llm_client
        self.memory = memory
        self.tools = tool_registry
        # Phase 4: ThemeMatcherTool for semantic style mapping
        self._theme_matcher: Optional[ThemeMatcherTool] = None

    # Style keyword mapping
    STYLE_KEYWORDS = {
        "樱花": ("sakura", "sakura-style"),
        "粉色": ("sakura", "sakura-style"),
        "萌系": ("sakura", "sakura-style"),
        "赛博": ("night", "cyberpunk-style"),
        "朋克": ("night", "cyberpunk-style"),
        "霓虹": ("night", "cyberpunk-style"),
        "科技": ("night", "cyberpunk-style"),
        "酷炫": ("night", "cyberpunk-style"),
        "薰衣草": ("lavender", "lavender-style"),
        "紫色": ("lavender", "lavender-style"),
        "薄荷": ("mint", "mint-style"),
        "清新": ("mint", "mint-style"),
        "绿色": ("mint", "mint-style"),
        "奶油": ("cream", "cream-style"),
        "米色": ("cream", "cream-style"),
        "像素": ("pixel", "pixel-style"),
        "复古": ("pixel", "pixel-style"),
        "极简": ("mono", "minimal-style"),
        "简约": ("mono", "minimal-style"),
        "千禧": ("millennial", "millennial-style"),
        "现代": ("millennial", "millennial-style"),
    }

    def get_system_prompt(self) -> str:
        return PLANNER_SYSTEM_PROMPT

    async def run(
        self,
        user_input: str,
        session: Session,
        context: Optional[Dict[str, Any]] = None
    ) -> AgentResponse:
        """Generate execution plan.

        Args:
            user_input: User's request
            session: Current session
            context: Optional context

        Returns:
            AgentResponse with ExecutionPlan
        """
        profile = session.get_profile() or {}

        # Determine intent
        intent = self._classify_intent(user_input, session)

        # Determine theme
        theme_id, skill_id = self._determine_theme(user_input, profile, context)

        # Generate action plan
        actions = self._generate_actions(intent, profile, theme_id)

        plan = ExecutionPlan(
            intent=intent,
            theme_id=theme_id,
            skill_id=skill_id,
            actions=actions,
            estimated_steps=len(actions),
            confidence=0.9,
        )

        # Save plan to session (use session metadata dict)
        if not hasattr(session, '_metadata'):
            session._metadata = {}
        session._metadata["execution_plan"] = plan.model_dump()

        return AgentResponse(
            session_id=session.id,
            response="",  # Planner doesn't respond directly
            action={
                "type": "plan",
                "data": {"plan": plan.model_dump()},
            },
            state=session.state.value,
        )

    def plan(
        self,
        user_input: str,
        profile: Dict[str, Any],
        session_state: str = "initial",
        context: Optional[Dict[str, Any]] = None,
    ) -> ExecutionPlan:
        """Synchronous planning (no LLM call, rule-based).

        Used by BuilderAgent pipeline for fast planning.
        """
        intent = self._classify_intent_simple(user_input, session_state)
        theme_id, skill_id = self._determine_theme(user_input, profile, context)

        actions = self._generate_actions(intent, profile, theme_id)

        return ExecutionPlan(
            intent=intent,
            theme_id=theme_id,
            skill_id=skill_id,
            actions=actions,
            estimated_steps=len(actions),
            confidence=0.8,
        )

    # ========================================================================
    # Planning helpers
    # ========================================================================

    def _classify_intent(self, user_input: str, session: Session) -> str:
        """Classify user intent using LLM."""
        try:
            # Fast keyword check first
            simple = self._classify_intent_simple(user_input, session.state.value)
            if simple in ("new_page", "modify_page"):
                return simple

            # Try LLM classification
            messages = [
                {"role": "system", "content": "只输出一个词: new_page, modify_page, query, 或 chat"},
                {"role": "user", "content": user_input},
            ]
            result = self.llm.chat(messages=messages)
            text = result.content.strip().lower() if hasattr(result, 'content') else str(result).lower()
            for keyword in ["new_page", "modify_page", "query", "chat"]:
                if keyword in text:
                    return keyword
        except Exception:
            pass

        return self._classify_intent_simple(user_input, session.state.value)

    def _classify_intent_simple(
        self, user_input: str, session_state: str
    ) -> str:
        """Simple rule-based intent classification."""
        user_lower = user_input.lower()

        # New page keywords
        for kw in ["生成", "创建", "做一个", "帮我做", "想要一个", "新建", "搭建", "制作"]:
            if kw in user_lower:
                return "new_page"

        # Modify keywords
        for kw in ["改", "换", "变", "修改", "换成", "调整", "优化", "更新", "替换"]:
            if kw in user_lower:
                return "modify_page"

        # Query keywords
        for kw in ["查", "看", "有什么", "列表", "搜索"]:
            if kw in user_lower:
                return "query"

        # Check session state
        if session_state in ("generating", "collecting", "confirming"):
            return "new_page"
        if session_state == "iterating":
            return "modify_page"

        return "chat"

    def _get_theme_matcher(self, mock: bool = False) -> ThemeMatcherTool:
        """Get or create ThemeMatcherTool instance."""
        if self._theme_matcher is None:
            self._theme_matcher = ThemeMatcherTool(
                llm_call=self.llm.chat if self.llm and hasattr(self.llm, 'chat') else None,
                mock=mock,
            )
        return self._theme_matcher

    def _determine_theme(
        self,
        user_input: str,
        profile: Dict[str, Any],
        context: Optional[Dict[str, Any]],
    ) -> tuple[str, Optional[str]]:
        """Determine theme and skill from input and profile.

        Phase 4: Uses ThemeMatcherTool when LLM is available,
        falls back to keyword-based matching otherwise.
        """
        # Check context override
        if context and context.get("theme_id"):
            tid = context["theme_id"]
            sid = f"{tid}-style" if tid not in ("sakura", "night") else None
            return tid, sid

        # Phase 4: Try ThemeMatcherTool with LLM
        if self.llm is not None:
            try:
                import asyncio
                mbti = profile.get("mbti") if profile else None
                history = None
                if profile and profile.get("style_preference"):
                    history = {"liked_themes": [profile.get("style_preference")]}

                matcher = self._get_theme_matcher()
                result = asyncio.get_event_loop().run_until_complete(
                    matcher.execute(ThemeMatcherInput(
                        user_input=user_input,
                        mbti=mbti,
                        history=history,
                    ))
                )

                if result.confidence >= 0.5 and result.theme_id in THEME_CATALOG:
                    theme_id = result.theme_id
                    skill_id = f"{theme_id}-style"
                    return theme_id, skill_id
            except Exception:
                pass

        # Fallback: Check profile style preference
        style_pref = profile.get("style_preference", "") if profile else ""
        for keyword, (theme, skill) in self.STYLE_KEYWORDS.items():
            if keyword in style_pref:
                return theme, skill

        # Fallback: Check user input for style keywords
        for keyword, (theme, skill) in self.STYLE_KEYWORDS.items():
            if keyword in user_input:
                return theme, skill

        # Default
        return "sakura", "sakura-style"

    def _generate_actions(
        self,
        intent: str,
        profile: Dict[str, Any],
        theme_id: str,
    ) -> List[ActionItem]:
        """Generate ordered action list for the plan."""
        actions = []

        if intent == "new_page":
            actions = [
                ActionItem(
                    tool="suggest_components",
                    args={"profile": profile, "theme_id": theme_id},
                    description="根据画像推荐组件",
                ),
                ActionItem(
                    tool="assemble_config",
                    args={"theme_id": theme_id},
                    description="拼装页面配置",
                ),
                ActionItem(
                    tool="auto_layout",
                    args={"canvas_width": 680},
                    description="自动布局组件位置",
                ),
                ActionItem(
                    tool="validate_config",
                    args={},
                    description="校验配置质量",
                ),
            ]

        elif intent == "modify_page":
            actions = [
                ActionItem(
                    tool="modify_config",
                    args={"instruction": ""},
                    description="修改现有配置",
                ),
                ActionItem(
                    tool="validate_config",
                    args={},
                    description="校验修改后的配置",
                ),
            ]

        return actions
