export function formatFileSize(bytes) {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}

export function sanitizeFileName(name) {
  return name
    .replace(/[<>:"/\\|?*]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'unnamed';
}

export function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 9);
}

export function validateImageFile(file, maxSize = 10 * 1024 * 1024) {
  const validTypes = ['image/png', 'image/jpeg', 'image/webp'];
  if (!validTypes.includes(file.type)) {
    return { valid: false, error: '不支持的格式，请上传 PNG、JPG 或 WEBP 图片' };
  }
  if (file.size > maxSize) {
    return { valid: false, error: `文件大小超过限制（最大 ${formatFileSize(maxSize)}）` };
  }
  return { valid: true };
}

export function loadImageFromFile(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error('图片加载失败'));
      img.src = e.target.result;
    };
    reader.onerror = () => reject(new Error('文件读取失败'));
    reader.readAsDataURL(file);
  });
}

export function generateThumbnail(img, maxSize = 80) {
  const canvas = document.createElement('canvas');
  const ratio = Math.min(maxSize / img.width, maxSize / img.height, 1);
  canvas.width = Math.max(1, Math.floor(img.width * ratio));
  canvas.height = Math.max(1, Math.floor(img.height * ratio));
  const ctx = canvas.getContext('2d');
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
  return canvas.toDataURL('image/png');
}

export function imageToImageData(img) {
  const canvas = document.createElement('canvas');
  canvas.width = img.width;
  canvas.height = img.height;
  const ctx = canvas.getContext('2d');
  ctx.drawImage(img, 0, 0);
  return ctx.getImageData(0, 0, canvas.width, canvas.height);
}

export function imageDataToDataURL(imageData) {
  const canvas = document.createElement('canvas');
  canvas.width = imageData.width;
  canvas.height = imageData.height;
  const ctx = canvas.getContext('2d');
  ctx.putImageData(imageData, 0, 0);
  return canvas.toDataURL('image/png');
}

export function imageDataToCanvas(imageData) {
  const canvas = document.createElement('canvas');
  canvas.width = imageData.width;
  canvas.height = imageData.height;
  const ctx = canvas.getContext('2d');
  ctx.putImageData(imageData, 0, 0);
  return canvas;
}

export function canvasToBlob(canvas) {
  return new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
}

export function generateTexturePackerJson(assets, sourceImageName, sourceWidth, sourceHeight) {
  const frames = {};
  for (const asset of assets) {
    frames[asset.name + '.png'] = {
      frame: { x: asset.x, y: asset.y, w: asset.w, h: asset.h },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: asset.w, h: asset.h },
      sourceSize: { w: asset.w, h: asset.h }
    };
  }
  
  return {
    meta: {
      app: '游戏UI素材工具',
      version: '1.0.0',
      image: sourceImageName,
      format: 'RGBA8888',
      size: { w: sourceWidth, h: sourceHeight }
    },
    frames: frames
  };
}

export function generateTexturePackerJsonArray(assets, sourceImageName, sourceWidth, sourceHeight) {
  const frames = assets.map(asset => ({
    filename: asset.name + '.png',
    frame: { x: asset.x, y: asset.y, w: asset.w, h: asset.h },
    rotated: false,
    trimmed: false,
    spriteSourceSize: { x: 0, y: 0, w: asset.w, h: asset.h },
    sourceSize: { w: asset.w, h: asset.h }
  }));
  
  return {
    meta: {
      app: '游戏UI素材工具',
      version: '1.0.0',
      image: sourceImageName,
      format: 'RGBA8888',
      size: { w: sourceWidth, h: sourceHeight }
    },
    frames: frames
  };
}

export function generateCssSprite(assets, sourceImageName) {
  let css = `/* Generated by 游戏UI素材工具 */\n`;
  css += `.sprite { background-image: url('${sourceImageName}'); }\n\n`;
  
  for (const asset of assets) {
    css += `.sprite-${asset.name} {\n`;
    css += `  width: ${asset.w}px;\n`;
    css += `  height: ${asset.h}px;\n`;
    css += `  background-position: -${asset.x}px -${asset.y}px;\n`;
    css += `}\n\n`;
  }
  
  return css;
}
