// 静静の部屋 — 复刻 anime-profile/index.html 的编辑器页面配置
// 用于演示编辑器能力

import { PageConfig, ComponentInstance } from '@/types'

export const jingjingProfileDemo: PageConfig = {
  id: 'demo_jingjing_001',
  title: '静静の部屋',
  slug: 'jingjing',
  theme: 'sakura',
  canvasWidth: 680,
  canvasHeight: 1200,
  background: {
    type: 'gradient',
    value: 'linear-gradient(135deg, rgba(242,167,179,0.05) 0%, rgba(180,167,214,0.05) 100%)',
  },
  metadata: {
    author: '静静',
    description: '夜空の星を数えるのが好き — 喜欢数夜空中的星星',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  components: [
    // ========== HERO SECTION ==========
    {
      id: 'hero_001',
      type: 'hero-section',
      x: 0,
      y: 0,
      width: 680,
      height: 160,
      zIndex: 1,
      avatar: '',
      name: '静静 / Jing Jing',
      signature: '夜空の星を数えるのが好き',
      signatureTypewriter: true,
      mbti: 'INFP',
      bloodType: 'AB型',
      zodiac: '♒水瓶座',
      age: '17岁',
      showGlow: true,
      glowColor: 'rgba(242,167,179,0.25)',
      backgroundGradient: 'linear-gradient(135deg, rgba(242,167,179,0.3) 0%, rgba(180,167,214,0.3) 100%)',
    },

    // ========== LEFT COLUMN: Profile Card ==========
    {
      id: 'container_profile',
      type: 'container',
      x: 0,
      y: 175,
      width: 220,
      height: 200,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_profile_title',
      type: 'text',
      x: 10,
      y: 183,
      width: 100,
      height: 16,
      zIndex: 3,
      content: '✦ プロフィール',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
      letterSpacing: 0.08,
    },
    {
      id: 'text_namae_label',
      type: 'text',
      x: 10,
      y: 208,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '名前',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_namae_value',
      type: 'text',
      x: 50,
      y: 208,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '静静',
      fontSize: 10,
      fontWeight: 'medium',
    },
    {
      id: 'text_tanjoubi_label',
      type: 'text',
      x: 120,
      y: 208,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '誕生日',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_tanjoubi_value',
      type: 'text',
      x: 160,
      y: 208,
      width: 50,
      height: 12,
      zIndex: 4,
      content: '2月14日',
      fontSize: 10,
    },
    {
      id: 'text_mbti_label',
      type: 'text',
      x: 10,
      y: 224,
      width: 40,
      height: 12,
      zIndex: 4,
      content: 'MBTI',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_mbti_value',
      type: 'text',
      x: 50,
      y: 224,
      width: 40,
      height: 12,
      zIndex: 4,
      content: 'INFP',
      fontSize: 10,
      fontWeight: 'medium',
    },
    {
      id: 'text_kuchiguse_label',
      type: 'text',
      x: 120,
      y: 224,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '口癖',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_kuchiguse_value',
      type: 'text',
      x: 160,
      y: 224,
      width: 50,
      height: 12,
      zIndex: 4,
      content: '「…嗯。」',
      fontSize: 10,
    },
    {
      id: 'text_shozsei_label',
      type: 'text',
      x: 10,
      y: 240,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '身長',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_shozsei_value',
      type: 'text',
      x: 50,
      y: 240,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '158cm',
      fontSize: 10,
    },
    {
      id: 'text_ketsueki_label',
      type: 'text',
      x: 120,
      y: 240,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '血液型',
      fontSize: 10,
      color: '#BBB',
    },
    {
      id: 'text_ketsueki_value',
      type: 'text',
      x: 160,
      y: 240,
      width: 40,
      height: 12,
      zIndex: 4,
      content: 'AB型',
      fontSize: 10,
    },

    // 属性标签
    {
      id: 'text_zokusei_label',
      type: 'text',
      x: 10,
      y: 264,
      width: 40,
      height: 12,
      zIndex: 4,
      content: '属性',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#B4A7D6',
    },
    {
      id: 'tag_attributes',
      type: 'tag-group',
      x: 10,
      y: 280,
      width: 200,
      height: 30,
      zIndex: 5,
      tags: ['天然', '内向', '毒舌', '社恐'],
      variant: 'filled',
      hoverColor: '#F2A7B3',
    },

    // 个人介绍
    {
      id: 'text_intro',
      type: 'text',
      x: 10,
      y: 315,
      width: 200,
      height: 30,
      zIndex: 6,
      content: '不擅长和人说话，但聊星星会停不下来。偶尔画画，大部分时间在发呆。',
      fontSize: 9,
      color: '#888',
    },

    // ========== LEFT COLUMN: Friends ==========
    {
      id: 'container_friends',
      type: 'container',
      x: 0,
      y: 365,
      width: 220,
      height: 60,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_friends_title',
      type: 'text',
      x: 10,
      y: 373,
      width: 80,
      height: 16,
      zIndex: 3,
      content: '✦ 友人帳',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
      letterSpacing: 0.08,
    },
    {
      id: 'friends_list',
      type: 'friends-list',
      x: 10,
      y: 392,
      width: 200,
      height: 30,
      zIndex: 7,
      friends: [
        { name: '月夜', intro: '流星雨伙伴', color: '#FFD700', avatar: '🌙' },
        { name: '苺', intro: '永远元气', color: '#FF6B9D', avatar: '🍓' },
        { name: '猫又', intro: '深夜搭档', color: '#8B5CF6', avatar: '🐱' },
        { name: '空', intro: '安静温柔', color: '#87CEEB', avatar: '☁' },
      ],
      variant: 'grid',
    },

    // ========== LEFT COLUMN: Season/Food ==========
    {
      id: 'container_season',
      type: 'container',
      x: 0,
      y: 440,
      width: 220,
      height: 100,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_season_title',
      type: 'text',
      x: 10,
      y: 448,
      width: 100,
      height: 16,
      zIndex: 3,
      content: '✦ 季節 · 食べ物',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
    },
    {
      id: 'text_season_label',
      type: 'text',
      x: 10,
      y: 468,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '☃ 喜欢的季节',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_season',
      type: 'tag-group',
      x: 10,
      y: 484,
      width: 200,
      height: 20,
      zIndex: 5,
      tags: ['冬', '雨天', '深夜', '雪天'],
    },
    {
      id: 'text_food_label',
      type: 'text',
      x: 10,
      y: 508,
      width: 80,
      height: 12,
      zIndex: 4,
      content: '🍰 喜欢的食物',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_food',
      type: 'tag-group',
      x: 10,
      y: 524,
      width: 200,
      height: 20,
      zIndex: 5,
      tags: ['草莓大福', '抹茶拿铁', '猫舌蛋糕', '芝士蛋糕'],
    },

    // ========== RIGHT COLUMN: Media ==========
    {
      id: 'container_media',
      type: 'container',
      x: 235,
      y: 175,
      width: 445,
      height: 160,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_media_title',
      type: 'text',
      x: 245,
      y: 183,
      width: 100,
      height: 16,
      zIndex: 3,
      content: '✦ 動画 · 电影',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
    },
    {
      id: 'text_anime_label',
      type: 'text',
      x: 245,
      y: 204,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '📺 TV动画',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_anime',
      type: 'tag-group',
      x: 245,
      y: 220,
      width: 200,
      height: 70,
      zIndex: 5,
      tags: ['葬送的芙莉莲', '孤独摇滚', 'Lycoris Recoil', '四月是你的谎言', '紫罗兰永恒花园', '魔法少女小圆', '物语系列', '春物'],
    },
    {
      id: 'text_movie_label',
      type: 'text',
      x: 460,
      y: 204,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '🎬 电影',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_movie',
      type: 'tag-group',
      x: 460,
      y: 220,
      width: 200,
      height: 70,
      zIndex: 5,
      tags: ['你的名字', '天气之子', '铃芽之旅', '萤火之森', '秒速5厘米', '夏目友人帐'],
    },

    // ========== RIGHT COLUMN: Oshi ==========
    {
      id: 'container_oshi',
      type: 'container',
      x: 235,
      y: 350,
      width: 445,
      height: 195,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_oshi_title',
      type: 'text',
      x: 245,
      y: 358,
      width: 80,
      height: 16,
      zIndex: 3,
      content: '✦ 我推 💕',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
    },
    {
      id: 'oshi_cards',
      type: 'oshi-card',
      x: 245,
      y: 380,
      width: 425,
      height: 150,
      zIndex: 7,
      characters: [
        { name: '芙莉莲', from: '葬送的芙莉莲' },
        { name: '后藤一里', from: '孤独摇滚' },
        { name: '锦木千束', from: 'Lycoris' },
        { name: '雪之下雪乃', from: '春物' },
        { name: '战场原荡美', from: '物语系列' },
        { name: '晓美焰', from: '小圆' },
        { name: '宫园薰', from: '四月谎言' },
        { name: '薇尔莉特', from: '紫罗兰' },
        { name: '阳菜', from: '天气之子' },
        { name: '三叶', from: '你的名字' },
        { name: '铃芽', from: '铃芽之旅' },
        { name: '名取周一', from: '夏目友人帐' },
      ],
      variant: 'grid',
      columns: 4,
    },

    // ========== RIGHT COLUMN: Music/Game/Books ==========
    {
      id: 'container_music',
      type: 'container',
      x: 235,
      y: 560,
      width: 445,
      height: 160,
      zIndex: 2,
      background: '#FFFFFF',
      borderRadius: 8,
      borderColor: '#EEE',
    },
    {
      id: 'text_music_title',
      type: 'text',
      x: 245,
      y: 568,
      width: 120,
      height: 16,
      zIndex: 3,
      content: '✦ 音楽 · ゲーム · 本',
      fontSize: 10,
      fontWeight: 'medium',
      color: '#BBB',
    },
    {
      id: 'text_music_label',
      type: 'text',
      x: 245,
      y: 588,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '🎵 音乐',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_music',
      type: 'tag-group',
      x: 245,
      y: 604,
      width: 200,
      height: 40,
      zIndex: 5,
      tags: ['YOASOBI', 'Aimer', 'ヨルシカ', 'n-buna', 'Lamp', 'Ayase'],
    },
    {
      id: 'text_game_label',
      type: 'text',
      x: 245,
      y: 648,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '🎮 游戏',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_game',
      type: 'tag-group',
      x: 245,
      y: 664,
      width: 200,
      height: 30,
      zIndex: 5,
      tags: ['原神', '崩铁', '空洞骑士', '塞尔达', '星露谷'],
    },
    {
      id: 'text_book_label',
      type: 'text',
      x: 460,
      y: 588,
      width: 60,
      height: 12,
      zIndex: 4,
      content: '📚 书籍',
      fontSize: 10,
      color: '#B4A7D6',
    },
    {
      id: 'tag_book',
      type: 'tag-group',
      x: 460,
      y: 604,
      width: 200,
      height: 50,
      zIndex: 5,
      tags: ['小王子', '银河铁道之夜', '人间失格', '挪威的森林', '海边的卡夫卡', '且听风吟'],
    },
    {
      id: 'text_music_quote',
      type: 'text',
      x: 530,
      y: 664,
      width: 130,
      height: 14,
      zIndex: 4,
      content: '「雨天喝茶最幸福」',
      fontSize: 9,
      color: '#888',
      textAlign: 'center',
    },

    // ========== FOOTER ==========
    {
      id: 'divider_footer',
      type: 'divider',
      x: 170,
      y: 740,
      width: 340,
      height: 20,
      zIndex: 1,
      variant: 'stars',
      color: '#F2A7B3',
    },
    {
      id: 'quote_footer',
      type: 'quote',
      x: 140,
      y: 765,
      width: 400,
      height: 30,
      zIndex: 2,
      text: '星は関係ない、自分で光れ — 与星星无关，自己发光吧',
      fontSize: 12,
      typewriterEffect: false,
    },

    // ========== STAR BACKGROUND ==========
    {
      id: 'star_bg',
      type: 'star-background',
      x: 0,
      y: 0,
      width: 680,
      height: 1200,
      zIndex: 0,
    } as any,
  ] as ComponentInstance[],
}
